[[override]]
  name = "github.com/kubernetes/client-go"
  branch = "release-8.0"

[[override]]
    name = "k8s.io/client-go"
    branch = "release-8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~v0.0.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.11.2"

[[constraint]]
  name = "github.com/DataDog/datadog-agent"
  version = "6.10.2"

[[override]]
  name = "github.com/kubernetes/apimachinery"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"
