apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: deploy
  name: deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: deploy
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        env:
        - name: SOCKET_PATH
          value: /network/var/run/network-tracer.sock
        image: charlyyfon/ebpf:metadata
        imagePullPolicy: IfNotPresent
        name: deploy
        resources: {}
        volumeMounts:
        - mountPath: /network/var/run
          name: network-var-run
      serviceAccountName: datadog-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - name: network-var-run
        hostPath:
          path: /network/var/run
          type: DirectoryOrCreate
---
# use the DirectoryOrCreate in the network tracer as well.
#     volumes:
#      - name: network-var-run
#        hostPath:
#          path: /network/var/run
#          type: DirectoryOrCreate
